services:
  stats-server:
    build: stats-service/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
      # - "5432:5432" //Idea
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: main-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver

  ewm-db:
    image: postgres:16.1
    container_name: ewn-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver